theme: jekyll-theme-chirpy
lang: tr-TR
timezone: Europe/Istanbul

title: ahmetak4n
tagline: Application Security Engineer, Golang, Java
description: ahmetak4n’s blog — application security, mobile and web security research.
url: https://ahmetakan.com
baseurl: ""
avatar: /assets/img/avatar.png
logo: /assets/img/avatar.png

author:
  name: Ahmet Akan
  twitter: ahmetak4n
  url: https://ahmetakan.com/about/

github:
  username: ahmetak4n

twitter:
  username: ahmetak4n
  card: summary_large_image

social:
  name: Ahmet Akan
  links:
    - https://github.com/ahmetak4n
    - https://x.com/ahmetak4n
    - https://medium.com/@ahmetak4n

toc: true
paginate: 10
paginate_path: /page/:num/

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      type: posts
    values:
      layout: post
      toc: true
      permalink: /:title/
  - scope:
      type: tabs
    values:
      layout: page
      permalink: /:title/

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  ignore:
    envs: [development]

exclude:
  - README.md
